---
# ./roles/app/tasks/install_docker_ce.yml

- import_tasks: app_yum.yml
  tags: [ app_yum ]
- import_tasks: app_pip.yml
  tags: [ app_pip ]
- include_tasks: app_geturl.yml
  tags: [ app_geturl ]
  with_items: "{{ geturl | default([]) }}"
- import_tasks: app_conf.yml
  tags: [ app_conf ]
- import_tasks: app_daemon.yml
  tags: [ app_daemon ]

# changelog
# 2019-09-09 initial by st3930
