---
# ./roles/common/tasks/yum_repo_docker_ce.yml
- name: yum install yum-util
  yum:
    name: yum-utils
    state: present

- name: yum_repository docker install
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/{{ansible_distribution|lower}}/docker-ce.repo"
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo

# changelog
## 2019-09-06 initial by st3930
