---
# .roles/docker/tasks/docker_compose.yml

- name: docker-compose create
  template:
    src: "{{ container_name }}/docker_compose.yml.j2"
    dest: "{{ conf_dir|default('/etc/docker-compose.d')}}/{{ container_name }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
    backup: yes

# changelog
# 2019-09-09 initial by st3930
